const currencies = [
    { name: 'XAF', symbol: 'FCFA', flag: '🇨🇲' },
    { name: 'NGN', symbol: '₦', flag: '🇳🇬' },
    { name: 'GHS', symbol: 'GH₵', flag: '🇬🇭' },
    { name: 'ZAR', symbol: 'R', flag: '🇿🇦' },
    { name: 'EGP', symbol: '£', flag: '🇪🇬' },
    { name: 'KES', symbol: 'KSh', flag: '🇰🇪' },
    { name: 'MAD', symbol: 'د.م', flag: '🇲🇦' },
    { name: 'TND', symbol: 'د.ت', flag: '🇹🇳' },
    { name: 'DZD', symbol: 'دج', flag: '🇩🇿' },
    { name: 'ETB', symbol: 'Br', flag: '🇪🇹' },
    { name: 'TZS', symbol: 'Sh', flag: '🇹🇿' },
    { name: 'UGX', symbol: 'USh', flag: '🇺🇬' },
    { name: 'USD', symbol: '$', flag: '🇺🇸' },
    { name: 'CAD', symbol: '$', flag: '🇨🇦' },
    { name: 'MXN', symbol: '$', flag: '🇲🇽' },
    { name: 'BRL', symbol: 'R$', flag: '🇧🇷' },
    { name: 'ARS', symbol: '$', flag: '🇦🇷' },
    { name: 'CLP', symbol: '$', flag: '🇨🇱' },
    { name: 'COP', symbol: '$', flag: '🇨🇴' },
    { name: 'EUR', symbol: '€', flag: '🇪🇺' },
    { name: 'GBP', symbol: '£', flag: '🇬🇧' },
    { name: 'CHF', symbol: 'CHF', flag: '🇨🇭' },
    { name: 'SEK', symbol: 'kr', flag: '🇸🇪' },
    { name: 'NOK', symbol: 'kr', flag: '🇳🇴' },
    { name: 'DKK', symbol: 'kr', flag: '🇩🇰' },
    { name: 'PLN', symbol: 'zł', flag: '🇵🇱' },
    { name: 'CZK', symbol: 'Kč', flag: '🇨🇿' },
    { name: 'HUF', symbol: 'Ft', flag: '🇭🇺' },
    { name: 'RON', symbol: 'lei', flag: '🇷🇴' },
    { name: 'AED', symbol: 'د.إ', flag: '🇦🇪' },
    { name: 'SAR', symbol: '﷼', flag: '🇸🇦' },
    { name: 'QAR', symbol: '﷼', flag: '🇶🇦' },
    { name: 'ILS', symbol: '₪', flag: '🇮🇱' },
    { name: 'TRY', symbol: '₺', flag: '🇹🇷' },
    { name: 'CNY', symbol: '¥', flag: '🇨🇳' },
    { name: 'JPY', symbol: '¥', flag: '🇯🇵' },
    { name: 'KRW', symbol: '₩', flag: '🇰🇷' },
    { name: 'INR', symbol: '₹', flag: '🇮🇳' },
    { name: 'IDR', symbol: 'Rp', flag: '🇮🇩' },
    { name: 'MYR', symbol: 'RM', flag: '🇲🇾' },
    { name: 'THB', symbol: '฿', flag: '🇹🇭' },
    { name: 'VND', symbol: '₫', flag: '🇻🇳' },
    { name: 'PHP', symbol: '₱', flag: '🇵🇭' },
    { name: 'SGD', symbol: '$', flag: '🇸🇬' },
    { name: 'HKD', symbol: '$', flag: '🇭🇰' },
    { name: 'AUD', symbol: '$', flag: '🇦🇺' },
    { name: 'NZD', symbol: '$', flag: '🇳🇿' },
    { name: 'RUB', symbol: '₽', flag: '🇷🇺' },
    { name: 'UAH', symbol: '₴', flag: '🇺🇦' },
    { name: 'BDT', symbol: '৳', flag: '🇧🇩' },
    { name: 'PKR', symbol: '₨', flag: '🇵🇰' },
    { name: 'LKR', symbol: 'Rs', flag: '🇱🇰' },
    { name: 'NPR', symbol: '₨', flag: '🇳🇵' },
];

export type Currency = typeof currencies[number];
export type CurrencyName = Currency['name'];
export default currencies;
